default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: earthster_code_challange_development

test:
  <<: *default
  database: earthster_code_challange_test

production:
  <<: *default
  database: earthster_code_challange_production
